### ISSUE TITLE
ERROR: p7zip isn't installed. Exiting...

### ISSUE THREAD

**Issue by senlinmuvs** [BL4CKvGHOST/Obevilion#1]
but:
bogon:Obevilion sen$ brew install p7zip

Warning: p7zip 16.02 is already installed

**Comment by BL4CKvGHOST** [comment]
Hello!
Obevilion script is tested on Linux and Mac os x
I Can Help You
What Operation System You Use?

**Comment by BL4CKvGHOST** [comment]
Just Updated The Script
and run with python3
